"""empty message

Revision ID: 5ed159c283c2
Revises: 9e0b4c9c69a5
Create Date: 2020-05-06 15:13:46.010864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed159c283c2'
down_revision = '9e0b4c9c69a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Genre_name_key', 'Genre', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Genre_name_key', 'Genre', ['name'])
    # ### end Alembic commands ###
